[env:blackpill_f401cc]
platform = ststm32
board = blackpill_f401cc
framework = arduino

upload_protocol = stlink
debug_tool = stlink

monitor_speed = 9600

lib_deps =
    marcoschwartz/LiquidCrystal_I2C